datasets:
  coco_caption_feat_dinov2_vitg14_bge_large: # name of the dataset builder
    data_type: features # [images|videos|features]

    build_info:
      features:
        storage:
          train:
            vis: features/dinov2_feature_extractor/vitg14/coco_caption/train.dpt
            text: features/bge_feature_extractor/large/coco_caption/train.dpt
