datasets:
  flickr30k_feat_dinov2_vitg14_cohere_v3: # name of the dataset builder
    data_type: features # [images|videos|features]

    build_info:
      features:
        storage:
          test:
            vis: features/dinov2_feature_extractor/vitg14/flickr30k/test.dpt
            text: features/cohere_feature_extractor/v3/flickr30k/test.dpt
